export const WEB_SCRAPING_RESPONSE={
    INTERNAL_SERVER_ERROR:'INTERNAL SERVER ERROR',
    SUCCESS:'DATA FETCH SUCCESSFULLY',
    NOT_FOUND:'DATA NOT FOUND',
    INVALID_URL:'INVALID URL..PLS CHECK AGAIN THE URL AND TRY AGAIN',
    INVALID_DATA:'INVALID DATA PROVIDED... PLS PROVIDE RIGHT URL, HTML_TAG, ATTRIBUTE_NAME'
}


export const HttpStatusCodes = {
    OK: 200,
    BAD_REQUEST: 400,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500
};